# Generated by Django 2.0.7 on 2018-08-08 00:32

from django.db import migrations
from ..models import Quote

quotes = [
    {
        "model": "quickstart.quote",
        "fields": {
            "quote": "You have to be interested to be interesting",
            "source": "Iris Apfel",
            "year": 2018
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "You don't find out who you are unless you work at it.",
            "source": "Iris Apfel",
            "year": 2018
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "More is more and less is a bore",
            "source": "Iris Apfel",
            "year": 2018
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Fashion can be bought. Style one must possess.",
            "source": "Edna Woolman Chase",
            "year": 2013
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Always Play Dressup!",
            "source": "Iris Apfel",
            "year": 2018
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Always Play Dressup!",
            "source": "Beth Jones"
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Life is gray and dull; you might as well have a little fun when you dress.",
            "source": "Iris Apfel"
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Fashion is like eating, you shouldn\'t stick to the same menu.",
            "source": "Kenzo Takada"
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "When I first moved to New York and I was totally broke, sometimes I would buy Vogue instead of dinner. I felt it fed me more.",
            "source": "Carrie Bradshaw",
            "year": 2001
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Personal style is curiosity about oneself.",
            "source": "Iris Apfel's nephew",
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "People will stare, make it worth their while.",
            "source": "Harry Winston"
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "You can have anything you want if you dress for it.",
            "source": "Edith Head"
        }
    },
    {
        "model": "quickstart.quote",
        "fields":   {
            "quote": "Style is a way to say who you are without having to speak.",
            "source": "Rachel Zoe",
            "year": 2015
        }
    }
  ]

def insert_qutoes(*argws):
    for quote in quotes:
        if quote['fields'].get('year'):
            Quote(quote=quote['fields']['quote'], source=quote['fields']['source'], year=quote['fields']['year']).save()
        else:
            Quote(quote=quote['fields']['quote'], source=quote['fields']['source'], year=None).save()

class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20180808_0059'),
    ]

    operations = [
        migrations.RunPython(insert_qutoes),
    ]